name: Deployment Test

on: 
  push:
    branches:
      - main

jobs: 
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node 18.15.0
        uses: actions/setup-node@v2.5.2
        with: 
          node-version: 18.15.0
      - name: npm install and npm run build
        run: |
          npm i
          npm run build
      
      - name: copy files
        uses: borisbreuer/scp-deploy-it@main
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./dist/*"
          target: "/test"
